name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 24.x
      uses: actions/setup-node@v3
      with:
        node-version: '24.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        path: 'dist/**/*'
